### ISSUE TITLE
InvalidAppSecretError despite reauthenticating

### ISSUE THREAD

**Issue by paulxuca** [vitiko98/qobuz-dl#125]
Hi! I believe qobuz recently changed their api and made the current way of getting a track URL no longer work. I'm getting InvalidAppSecretError despite reauthenticating.

Cheers!

**Comment by jaythib** [comment]
Same issue here.

**Comment by nkopas** [comment]
I was able to bypass this problem by hardcoding the secret at the bottom of qopy.py:
```
    def cfg_setup(self):
#        for secret in self.secrets:
#            if secret and self.test_secret(secret):
#                self.sec = secret
#                break
        self.sec = "979549437fcc4a3faad4867b5cd25dcb"
        if self.sec is None:
            raise InvalidAppSecretError("Invalid app secret.\n" + RESET)
```

**Comment by kokorickos** [comment]
> self.sec = "979549437fcc4a3faad4867b5cd25dcb"

Hi dear nkopas! Many thanks - it works!

**Comment by pinus2** [comment]
You can hardcoding or modify only the config.ini secret field like this:
[image]https://user-images.githubusercontent.com/50369938/143594858-15f9e9b6-bff7-46a7-87bb-9f0cea588ff7.png[/image]

**Comment by KaptainKankle** [comment]
> I was able to bypass this problem by hardcoding the secret at the bottom of qopy.py:
> 
> ```
>     def cfg_setup(self):
> #        for secret in self.secrets:
> #            if secret and self.test_secret(secret):
> #                self.sec = secret
> #                break
>         self.sec = "979549437fcc4a3faad4867b5cd25dcb"
>         if self.sec is None:
>             raise InvalidAppSecretError("Invalid app secret.\n" + RESET)
> ```

This also worked for me!  Thank you!

**Comment by chrschrschrs** [comment]
the config.ini file doesn't seem to be at the specified path after resetting (qobuz -r). where can i find it? what could be the problem. editing qopy.py doesn't solve the problem for me.

**Comment by pinus2** [comment]
> the config.ini file doesn't seem to be at the specified path after resetting (qobuz -r). where can i find it? what could be the problem? only editing qopy.py doesn't solve the problem for me.
> 
> Getting this error
> 
> C:\Users\XXXX>qobuz-dl dl [albumlink] Logging... Logged: OK Membership: Studio Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\qobuz-dl.exe__main__.py", line 7, in File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\qobuz_dl\cli.py", line 174, in main qobuz.initialize_client(email, password, app_id, secrets) File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\qobuz_dl\core.py", line 73, in initialize_client self.client = qopy.Client(email, pwd, app_id, secrets) File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\qobuz_dl\qopy.py", line 40, in **init** self.cfg_setup() AttributeError: 'Client' object has no attribute 'cfg_setup'

@chrschrschrs config.ini probably is in appdata\roaming\qobuz-dl  but i dont know exactly because  i use Linux

**Comment by vitiko98** [comment]
I just found the problem. The `test_secret` method was always returning `True`, even with wrong or empty `secret` strings-. The method was updated. It should work now. Thanks!

**Comment by letotor** [comment]
a New version of qobuz-dl here:  @[qobuz-dl](https://pypi.org/project/qobuz-dl/) :
`pip3 install --upgrade qobuz-dl`
or
```
pip3 uninstall qobuz-dl
pip3 install --upgrade qobuz-dl
```

enjoy it ;)

**Comment by chrschrschrs** [comment]
new version fixed all issues for me! thanks so much!

**Comment by jaythib** [comment]
> I just found the problem. The `test_secret` method was always returning `True`, even with wrong or empty `secret` strings. The method was updated. It should work now. Thanks!
> 
> Don't forget to run `pip install qobuz-dl --upgrade`

Thank you for the fix!
