### ISSUE TITLE
[REQ] Save files in separated folders when an album contains more than 1 CD

### ISSUE THREAD

**Issue by cattivik66** [vitiko98/qobuz-dl#13]
It would be nice to have the files saved in subfolders when an album contains more than 1 CD.
Specially because some albums have the same track name (in different version) on different CDs, and this cause the first file to be overwritten.

In addition, it would be nice to have an option that checks if a file already exists to avoid duplicated downloads (ex.: to resume the download of an album that was previously interrupted).

**Comment by vitiko98** [comment]
Done!
