### ISSUE TITLE
Permission Error: [Errno 13] Permission Denied

### ISSUE THREAD

**Issue by Maxnforcer** [vitiko98/qobuz-dl#132]
I keep getting this:
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/UNKNOWN
sysconfig: /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9
WARNING: Additional context:
user = False
home = None
root = None
prefix = None

After installing "pip3 install --upgrade qobuz-dl" any ideas ?  Running on Mac Air, Big Sur.

**Comment by Tecko71** [comment]
I have something similar: OSError [Errno 30] Read-only file system:

**Comment by vitiko98** [comment]
That's related to your OS, not the app. Please search for python permission info for your OS.
