### ISSUE TITLE
Error getting release: This release is not streamable. Skipping...

### ISSUE THREAD

**Issue by yogourts** [vitiko98/qobuz-dl#146]
Logging...
Logged: OK
Membership: Studio
Set max quality: 7 - 24 bit, <96kHz

Error getting release: This release is not streamable. Skipping...

**Comment by yogourts** [comment]
what can i do

**Comment by TheMelmacian** [comment]
Nothing. If a track can't be streamed you can't download it.

**Comment by LETRA** [comment]
It is happening more and more often. This is something to pay attention to.
