### ISSUE TITLE
[REQ] Handling different qualities

### ISSUE THREAD

**Issue by Fukitsu** [vitiko98/qobuz-dl#15]
An option to download only the albums in the highest quality or both and save them in folders with the quality appended. Some artists have the same album twice but in different qualities and if an album is already downloaded it overwrites it even if the new one is in lower quality

**Comment by vitiko98** [comment]
I would appreciate an artist example of this.

**Comment by Fukitsu** [comment]
RC Succession for example has a few albums with the same name but in different qualities
http://open.qobuz.com/artist/6735153

**Comment by vitiko98** [comment]
I think adding bit depth info to the download folder will fix this problem. Let's see.

**Comment by vitiko98** [comment]
Done!

**Comment by Fukitsu** [comment]
Thank you, just something I noticed is that it adds 'Hi-Res' to the folder name even if the album itself isn't in Hi-Res quality, is it because of the preferred quality selected in the config file?
For example with this artist: http://open.qobuz.com/artist/2033892
All the folders are have 'Hi-Res' appended even though not all of them are in Hi-Res but if the selected quality is the default one it appends FLAC or Hi-Res correctly. Could it be possible to instead have the actual quality appended like 16bit/44.1kHz or a custom name scheme. Also didn't want to open a new issue issue but can you add an option to download the artist cover/art when downloading a whole artist?
