### ISSUE TITLE
How to download DSD?

### ISSUE THREAD

**Issue by martystack** [vitiko98/qobuz-dl#167]
It says its there.....

Downloading: Friday Night in San Francisco (16-bit, 24/88.2, 24/176.4 ADM, DSD)
Quality: FLAC (24/176.4)

67.4k/67.4k /// cover.jpg
492M/492M /// Mediterranean Sundance / Rio Ancho  
359M/359M /// Short Tales of the Black Forest  
330M/330M /// Frevo Rasgado  
373M/373M /// Fantasia Suite  
167M/167M /// Guardian Angel

**Comment by Ghoost666** [comment]
maybe the original is DSD but i think Qobuz wont stream in DSD

**Comment by vitiko98** [comment]
Qobuz API does not support DSD.
