### ISSUE TITLE
no qobuz-dl.exe

### ISSUE THREAD

**Issue by Tecko71** [vitiko98/qobuz-dl#177]
After installing en confirm indipendicies qobuz-dl.exe can not be found (win11)

qobuz-dl.exe : The term 'qobuz-dl.exe' is not recognized as the name of a cmdlet, function, script file, or operable pr
ogram. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ qobuz-dl.exe dl

**Comment by vitiko98** [comment]
Please search for info about python's path in windows.
