### ISSUE TITLE
Add Extra fields to metadata

### ISSUE THREAD

**Issue by steve-o-matic** [vitiko98/qobuz-dl#18]
Again for example album: https://play.qobuz.com/album/0002894814756

Adding Composer and the main piece name (that I don't know in which field it is stored) to the metadata will be most appreciated.

**Comment by vitiko98** [comment]
Piece's name is inside "work". I've added support for this tag in both mp3 and FLAC.

**Comment by steve-o-matic** [comment]
Thanks for your speedy work on this!
I was just trying the new version of your software and I don't seem to have the information in the tags (tested with both FLAC and MP3). 

From the example album, the first track now reads : 1. Allegro molto moderato (None) and doesn't mention "Fantasy in F minor, D. 940 (Op.103) for piano duet (Franz Schubert)" anywhere on the track.

**Comment by steve-o-matic** [comment]
Suggested song title: Fantasy In F Minor, D. 940 (Op.103) For Piano Duet: 1. Allegro Molto Moderato
With Schubert going it its own field like it is.
