### ISSUE TITLE
hi i upgraded to the latest release and its not working properly, it used to run seanlessly but now, stalls and d/ls tracks by packets, i've not seen this before, should i go back to an older version? i'm not sure how to uninstall qobuz-dl

### ISSUE THREAD

**Issue by expatoz** [vitiko98/qobuz-dl#188]

**Comment by crackheadakira** [comment]
You should be able to download an older version with `pip install --upgrade qobuz-dl==0.9.9.8`

**Comment by expatoz** [comment]
> You should be able to download an older version with `pip install --upgrade qobuz-dl==0.9.9.8`
Cheers thanks, python is out of my league
