### ISSUE TITLE
Hi-Res folder naming

### ISSUE THREAD

**Issue by steve-o-matic** [vitiko98/qobuz-dl#20]
This label seems to appear in all album folder names as high res even if they are CD quality. Maybe it is taking this from the command line options instead of the CDs themselves?

**Comment by vitiko98** [comment]
The problem is that ` qobuz-dl` can't get track info at the moment of creating the root folder, so we just guess the quality from the `--quality` flag.

**Comment by steve-o-matic** [comment]
Personally I would rather not have anything on the folder name then as it is just confusing now (but renames are easy). If the current behaviour is intentional, Feel free to close.

**Comment by vitiko98** [comment]
See #15.

In any case, I will try to do something.

**Comment by steve-o-matic** [comment]
I see. The thing is the automatic 'downsampling' to highest available quality. If selecting a release that is only available at CD quality but the command line is set for high res it will be incoherent in the naming. Since you are printing the actual rate when downloading, it should be possible to get this info. Maybe the easiest for now is to activate this behaviour with another command line flag instead of it being default behaviour.

**Comment by cattivik66** [comment]
Perhaps the downloads can be saved on a temp folder ("Band - AlbumName [year] [temp]") and, once downloaded, the folder could be renamed with the final name, using the real information of the album?

**Comment by vitiko98** [comment]
Done

**Comment by zozzza** [comment]
@vitiko98 Suggestion: maybe it is not appropriate to report the actual quality in bits and kHz instead of "FLAC" and "Hi-Res"? The reason is simple, the files downloaded in two, or three, different qualities are always in FLAC format with the exception of MP3 files of course.
