### ISSUE TITLE
Where is the default download location?

### ISSUE THREAD

**Issue by peworjlfk** [vitiko98/qobuz-dl#201]
As the title above says. I download some albums before I relaized I left the download location to default and now can't find my songs.

**Comment by Novem30** [comment]
I believe it depends where it is running from, for example mine is in

`C:\Users\UserName\AppData\Roaming\Python\Python311\Scripts\Qobuz Downloads\`

**Comment by vitiko98** [comment]
> I believe it depends where it is running from, for example mine is in
> 
> `C:\Users\UserName\AppData\Roaming\Python\Python311\Scripts\Qobuz Downloads\`

This is correct.
