### ISSUE TITLE
'/' in album name creating new directories

### ISSUE THREAD

**Issue by LikeAwnestly** [vitiko98/qobuz-dl#212]
If there is a / in an album name it will create multiple directories. For example, the album "1,039 / Smoothed out Slappy Hours (U.S. Version)" by Green Day has an / which should be ignored or replaced with a non-illegal filename character but it simply makes a new directly like this: 

Green Day / 1039 /  Smoothed out Slappy Hours (U.S. Version) / 01. Song

It should be : 

Green Day / 1039-Smoothed out Slappy Hours (U.S. Version) / 01. Song

Is there something you can put in the config.ini file that will replace or ignore "/" in file or folder names?

**Comment by morbificagent** [comment]
Oh, i have opened a issue for that too some minutes ago ;-)

Did you find any workaround for this?
