### ISSUE TITLE
Management of different versions of the same album

### ISSUE THREAD

**Issue by cattivik66** [vitiko98/qobuz-dl#22]
Sometimes there are different versions of the same album.
For example, one version could be "clean" when another one could be "explicit".

As those albums have all the same name/year/quality/etc, they are stored in the same folder.

An example: "Madonna - Rebel Heart"
https://play.qobuz.com/album/0060254722641 - Clean version, 19 tracks
https://play.qobuz.com/album/0060254723453 - Mature version, 14 tracks
https://play.qobuz.com/album/0060254730346 - 6 tracks
https://play.qobuz.com/album/0060254724639 - Clean version, 14 tracks
https://play.qobuz.com/album/0060254726534 - Mature version, 25 tracks.

At the end you get everything in a single folder.
Not sure if this is intended or not, and how could be managed.
On way would be to add, on the folder name, the id of the album. Of course this would produce file duplicates and a waste of space & bandwidth, but would guarantee to have all tracks and to not mix different albums on the same folder.

Anyway, there is also the problem that some albums have different version of the same song on the same track number, resulting in missing some versions of the track.

This could be also "fixed" by implementing in the meantime a new feature, giving the possibility to configure the generated folder name & track name:
Something like "[{year_release}] [{quality}] {optional_tags} {album_name} [{album_id}]".
In this way the user can decide if store everything in the same folder or not, and how to organize the folder.
For example I prefer to have the year release at the beginning of the folder name.

**Comment by vitiko98** [comment]
Just noticed Qobuz returns a `parental_warning` key in some releases. I've added a workaround for this issue. For example, `qobuz-dl` will create folders like `Future - DS2 (Deluxe) (Explicit) [2015] [FLAC]` for albums with `parental_warning`. 

```console
victor@slackware ~/dev/qobuz-dl/Qobuz Downloads $ ls -1
Madonna - Rebel Heart (Deluxe) [2015] [FLAC]
Madonna - Rebel Heart (Explicit) [2015] [FLAC]
```


> Something like "[{year_release}] [{quality}] {optional_tags} {album_name} [{album_id}]".
> In this way the user can decide if store everything in the same folder or not, and how to organize the folder.
> For example I prefer to have the year release at the beginning of the folder name.

I suggest you to use [beets](https://github.com/beetbox/beets) for such task. Qobuz API is kinda irregular (fields here, fields not here) to produce desirable results with folder naming and alike.
