### ISSUE TITLE
Question: DL just cover art?

### ISSUE THREAD

**Issue by ZBiener** [vitiko98/qobuz-dl#224]
Hi All,
Is it possible to download only the cover image associated with a track?
(I think this is not currently possible, but I wonder if it a limitation of the script or of the Qobuz API. Does anyone know?)
Thanks.

**Comment by cmd64** [comment]
Yeah, it is possible. You need to do some changes download_release and download_track methods at downloader.py
Make build again. Download source code and move C:\qobuz-dl-master. Open terminal as administrator.
cd C:\qobuz-dl-master
py -m build
pip install C:\qobuz-dl-master\dist\qobuz_dl-0.9.9.10-py3-none-any.whl --force-reinstall --no-cache-dir

download_release
find this line
dirn = os.path.join(self.path, sanitized_title)

replace with this
release_type = meta.get("release_type").upper()
dirn = os.path.join(self.path, release_type, sanitized_title)

download_track
find this line
dirn = os.path.join(self.path, sanitized_title)

replace with this
release_type = meta["album"]["release_type"].upper()
dirn = os.path.join(self.path, release_type, sanitized_title)

**Comment by ZBiener** [comment]
Thanks! I will report back if there are unexpected issues.
Zvi
