### ISSUE TITLE
Option to skip single & ep, and "Various Artists" when downloading a specific artist

### ISSUE THREAD

**Issue by cattivik66** [vitiko98/qobuz-dl#23]
When downloading everything about an artist, it would be nice to have the possibility to skip single & EP.
Same thing with albums where the artist is present just in few tracks and not the whole album.

The idea is that, when downloading an artist, the folder contains only albums that starts with the artist name and it does not have any EPs & singles.

**Comment by vitiko98** [comment]
I know it will be great but afaik Qobuz doesn't return release type info.

**Comment by vitiko98** [comment]
Looks like `product_type` will do the trick.

**Comment by vitiko98** [comment]
Done.

Thanks for the suggestion
