### ISSUE TITLE
Cover Art

### ISSUE THREAD

**Issue by zozzza** [vitiko98/qobuz-dl#24]
Hi there,
is there any chance to download the cover art in HQ? I noticed that the covers are downscaled by qobuz, you can see the string  "_600.jpg" at the end of any image link for example. Maybe mitmproxy can help?
Thank you.

**Comment by vitiko98** [comment]
That's the max quality Qobuz API returns. There's nothing we can do about it.

**Comment by zozzza** [comment]
> That's the max quality Qobuz API returns. There's nothing we can do about it. :/

"Chimera" downloaded the covers in high resolution so I think it's possible to do it, the problem is that I don't have the chimera master and I don't know how it works. Please investigate.

**Comment by vitiko98** [comment]
You were right! Please go to #25.
