### ISSUE TITLE
Cover Artwork in original resolution

### ISSUE THREAD

**Issue by thomrnowtea** [vitiko98/qobuz-dl#25]
Hello, there is a way to embed the artwork of any album in the original resolution and not in 600x600?
Only thing I know is that you can get the original resolution taking the url of any Qobuz album cover, for example,"cover_600.jpg" and changing it to "cover_org.jpg".
Is there anything you can do with that information for getting the original cover resolution with qobuz-dl?

**Comment by vitiko98** [comment]
Didn't know about it. I'll take a look.

**Comment by zozzza** [comment]
Oh nice @vitiko98 so I think it is better to download the original artwork instead of the resized one. What do you say? I think the code is pretty easy to integrate, Thanks.
@thomrnowtea thanks for the trick!

**Comment by vitiko98** [comment]
Done!

**Comment by zozzza** [comment]
> Done!

Thank you so much!

**Comment by vitiko98** [comment]
Covers won't be downloaded in their original size anymore by default as they are too big. If you still want to download in the original size, just set the flag `--og-cover` after running a `qobuz-dl` command.

_Originally posted by @vitiko98 in https://github.com/vitiko98/qobuz-dl/issues/36#issuecomment-747832745_
