### ISSUE TITLE
Work field on albums

### ISSUE THREAD

**Issue by steve-o-matic** [vitiko98/qobuz-dl#26]
Thanks for your speedy work on this!
I was just trying the new version of your software and I don't seem to have the information in the tags (tested with both FLAC and MP3). 

From the example album, the first track now reads : 1. Allegro molto moderato (None) and doesn't mention "Fantasy in F minor, D. 940 (Op.103) for piano duet (Franz Schubert)" anywhere on the track.

_Originally posted by @steve-o-matic in https://github.com/vitiko98/qobuz-dl/issues/18#issuecomment-743969789_

**Comment by vitiko98** [comment]
Got it. I think the work title would look better in the track title instead of a "work" FLAC/MP3 field that probaly doesn't work with most music players.

**Comment by vitiko98** [comment]
In the next release, tracks will look like this:

```
General
Complete name                            : 01. Aria  Sarabande (Remastered).flac
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
File size                                : 9.69 MiB
Duration                                 : 3 min 4 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 440 kb/s
Album                                    : Bach: The Goldberg Variations (1981) - Gould Remastered
Album/Performer                          : Glenn Gould
Track name                               : Goldberg Variations, BWV 988: Aria : Sarabande (Remastered)
Track name/Position                      : 1
Track name/Total                         : 32
Performer                                : Glenn Gould
Composer                                 : Johann Sebastian Bach
```

**Comment by steve-o-matic** [comment]
Thanks! That looks pretty perfect! (Good choice of track too!)
