### ISSUE TITLE
Download by text file not working

### ISSUE THREAD

**Issue by thomrnowtea** [vitiko98/qobuz-dl#27]
(base) C:\Users\Usuario>qobuz-dl dl -e "C:\Users\Usuario\Desktop\album_list.txt"
Logging...
Logged: OK
Membership: Studio

Invalid url: "C:\Users\Usuario\Desktop\album_list.txt". Use urls from https://play.qobuz.com!

**Comment by vitiko98** [comment]
Done.

Thanks for reporting!
