### ISSUE TITLE
Support for downloading DSD & DXD format from qobuz

### ISSUE THREAD

**Issue by Pehnyakka** [vitiko98/qobuz-dl#288]
Qobuz recently came out with an option to download the DSD & DXD files of certain releases, not for streaming but available in download store, can you add an option to set download quality in qobuz-dl so that it will rip the DSD version or the album? One example is Michael Jackson - Thriller.
Available in DSD64 in the qobuz download store

Kind regards

**Comment by Kilgore-Trout1989** [comment]
Save your time. Qobuz-dl no longer works. Qobuz locked it down

**Comment by Pehnyakka** [comment]
Oh but it works just fine for me haha! I still use it!

**Comment by Kilgore-Trout1989** [comment]
Do you live in the US?

**Comment by Pehnyakka** [comment]
Europe

**Comment by Kilgore-Trout1989** [comment]
Must be depending on location then. I’m in the US

**Comment by Kilgore-Trout1989** [comment]
Nevermind, it's working for me now. It was operator error

**Comment by Covfefee9000** [comment]
[Kilgore-Trout1989](https://github.com/Kilgore-Trout1989) has effectively shown his ignorance and killed this thread. Please delete your stupid comments. Qobuz-dl works fine, as always.

We are still hoping for an update to downlaod DSD files!

**Comment by Kilgore-Trout1989** [comment]
Get a grip. I admitted it was my error. Jeez don't you have anything better to do than police GitHub posts?

**Comment by vitiko98** [comment]
Sadly, the only way to get DSD files would be if they were available to stream from their clients. We can't get anything from the store.

As noted in this [Qobuz article](https://help.qobuz.com/en/articles/222620-what-are-dsd-and-dxd):
> New Feature: The DSD and DXD formats are now also available for purchase; these formats are not available for streaming
