### ISSUE TITLE
Playlist m3u for playlist download - enhancement

### ISSUE THREAD

**Issue by steve-o-matic** [vitiko98/qobuz-dl#31]
Would it be possible to create a relative path M3U file for each playlist when they are downloaded?
I have written a hacky thing for myself, but it would be nice if the software did it by itself automatically.

**Comment by vitiko98** [comment]
Will take a look

**Comment by vitiko98** [comment]
Added! Test it in `dev` branch.

**Comment by steve-o-matic** [comment]
Thanks for the speedy implementation. Works great!

Personally I would prefer:
1) relative paths (so that it can all be moved as a block)
2) the file saved inside the folder containing the playlist as opposed to just outside. 
Point 1 is far more relevant than point 2.

**Comment by vitiko98** [comment]
> 1. relative paths (so that it can all be moved as a block)
> 2. the file saved inside the folder containing the playlist as opposed to just outside.

That's excellent.

Keep it up with the good feature ideas.
