### ISSUE TITLE
No cover in metadata on multiple discs.

### ISSUE THREAD

**Issue by zozzza** [vitiko98/qobuz-dl#34]
When you try to download a release consisting of several discs the cover is not inserted in the metadata.

**Comment by vitiko98** [comment]
Post an example. And don't forget to enable the `-e` at the end of the command.

**Comment by zozzza** [comment]
> Post an example. And don't forget to enable the `-e` at the end of the command.

I noticed it while using VLC on android, I thought it was a problem due to the creation of the library; I just checked with "ffmpeg", all albums that are composed of multiple discs do not have the cover in the metadata and ofc I used "--embed-art" or "-e" via bash shell. The tool doesn't crash anyway.

**Comment by vitiko98** [comment]
`qobuz-dl` should print a message like `Error embedding image: <exception>`. Please try to reproduce.

**Comment by zozzza** [comment]
Nope, i don't get this message and I don't see anything strange through "gdb". Did you check yourself?

**Comment by cattivik66** [comment]
Actually there isn't any cover stored in the file even if the album has only 1 CD.
In fact if you move the FLAC file to a new location without the cover.jpg file, and you open it with a player, the cover would not be displayed.

**Comment by vitiko98** [comment]
> Actually there isn't any cover stored in the file even if the album has only 1 CD.
> In fact if you move the FLAC file to a new location without the cover.jpg file, and you open it with a player, the cover would not be displayed.

You trippin' hard. I tried moving the file to another location and the cover art is still there:

![2020-12-16-131314_305x76_scrot](https://user-images.githubusercontent.com/59455966/102382158-7da1b900-3fa0-11eb-9bca-6d129c936d9c.png)

```
Cover type                               : Cover (front)
Cover MIME                               : image/jpeg
```

Anyway, @zozzza was right about covers not showing with multiple discs. This issue is closed in `dev` branch.
