### ISSUE TITLE
Only download Hi-Res and skip lower versions

### ISSUE THREAD

**Issue by Gamer4Life2020** [vitiko98/qobuz-dl#35]
Thanks for this as I found it by accident. Was using the one from Sorrow before they pulled it.
So far so good, but would there be a way to skip already downloaded songs. Like if I choose -q 27 it would only get the hi-res per the flag and skip the lower versions, but if needed also download the other versions that a hi-res isn't available.

If not no biggie as I can make a txt with what I would like. I just thought it would be nice to say pick and artist and let it get the highest quality and not have two copies one hi-res and one not.

**Comment by vitiko98** [comment]
Good idea! Definitely easy to implement.
