### ISSUE TITLE
only first 500 items of playlist get downloaded

### ISSUE THREAD

**Issue by steve-o-matic** [vitiko98/qobuz-dl#40]
Still trying to download the same playlist for local shuffling. Just realised only first 500 items are recognised for download. Is this an API limitation?

**Comment by vitiko98** [comment]
This method should handle more than 500 items:

https://github.com/vitiko98/qobuz-dl/blob/3919984a75b85a42d68105479a66e59b8184be30/qobuz_dl/qopy.py#L126-L140

In any case, I don't endorse massive downloads. Qobuz may nuke the tokens. :p

**Comment by steve-o-matic** [comment]
Thanks. I am playing around and learning from it, but I guess I have reached stupidity point. I'll be reasonable from now on. I just wish they would release a linux app. Their web thing is a buggy resource hog.
