### ISSUE TITLE
Remove disc tag and others.

### ISSUE THREAD

**Issue by zozzza** [vitiko98/qobuz-dl#44]
Please consider the following changes:
1. Remove the "disc" entry (metadata) when the release is not composed of multiple discs, many releases are only EPs, singles, etc.;
2. Add the artist name to each file after the track number because many releases are compilations or many tracks are collaborations between different artists, so know the artist name without having to check the metadata or with an audio player;
3. Add the day of publications (metadata) in "date" along with the year or revert to "year" by adding "date";
4. Add "Label" tag in metadata;
5. Replace the entry "FLAC", "Hi-Res", etc. with the actual bits/kHz; please consider replacing square brackets with round brackets to the year;
6. Improve track names, some information is not added. Example: `https://play.qobuz.com/album/p39tju9ljy8ra` "(Acoustic Bossa Version)" is missing.

Thank you.

**Comment by vitiko98** [comment]
Good suggestions!

1. Ok
2. Ok
3. Ok
4. Ok
5. Only for Hi-Res downloads (the only ones in which bits/kHz vary)
6. Ok

**Comment by vitiko98** [comment]
Closed in new version

**Comment by zozzza** [comment]
>     5. Only for Hi-Res downloads (the only ones in which bits/kHz vary)
> 
I still have the idea of writing bits and KHz for 16bit files too, however I think it would be better to write "Lossless" instead of "FLAC" for 16-Bit files as it indicates the file format and not the quality '? 24-bit files are also in FLAC!

I mean: `320kbits / 16-Bit-44.1 kHz / 24-Bit-44.1 kHz / etc.` or `320 / 16-44.1 / 24-44.1`

**Comment by zozzza** [comment]
>     5. Only for Hi-Res downloads (the only ones in which bits/kHz vary)
>
I still have the idea of writing bits and KHz, however I think it would be better to write "Lossless" instead of "FLAC" because 24-bit files are also in "FLAC" file format and "Lossy" to the MP3 files.
.
Anyway I think these are the best solutions: `Lossy / Lossless / 24Bit-44.1kHz / etc` or `Lossy / Lossless / Hi-Res`.

**Comment by vitiko98** [comment]
I use FLAC because is the standard format for 16Bit Lossless in most music trackers.

I suggest you to try [beets](https://github.com/beetbox/beets) for advanced naming.
