### ISSUE TITLE
New releases.

### ISSUE THREAD

**Issue by zozzza** [vitiko98/qobuz-dl#45]
Scenario: today I downloaded a whole small record label, on his facebook page I read that there will be 3 new releases next month.
.
Idea: the tool save a text file with all links of the downloaded releases today if add the argument, for example. "`--dl-links`", next month when I use the "download mode" with the link of the record label add the argument "`--links`" and the path text file. The tool compare the links contained in the text file and download the missing links.
_
Example: `qobuz-dl dl -q 27 https://play.qobuz.com/label/124345 --links /path/of/your/file`
It could be a good idea?

**Comment by vitiko98** [comment]
It's a good idea. However, if we want to skip already downloaded releases, a portable sqlite database would perform better. 

Let me see what I can do.

**Comment by zozzza** [comment]
Oh, thank you so much! One question, what is the path of the "qobuz_dl.db" file?

**Comment by vitiko98** [comment]
> Oh, thank you so much! One stupid question, what is the path of the "qobuz_dl.db" file (linux)? If I have to backup the file to be able to use it on another machine, for example, can I just copy it to the original path?

`~/.config/qobuz-dl/` (`$HOME/.config/qobuz-dl`)

> I also discovered that if there are two releases by the same artist with the same name but with different songs, for example the single and the album containing the remixes, one of the two is skipped. Why?

Try to reproduce and open an issue for this. Don't forget to paste the output.
