### ISSUE TITLE
Add Total Disc and Disc Number to tags if available

### ISSUE THREAD

**Issue by Gamer4Life2020** [vitiko98/qobuz-dl#46]
I found on multi-disc sets while it does put in separate folders, the total disc and disc numbers are not in the tags.
So when renaming or organizing with Picard it puts all the tracks in the same folder. No a huge deal as I can recheck or manually fix, but just a thought.  Tags show as totaldisc and discnumber.

**Comment by vitiko98** [comment]
That's already included:

https://github.com/vitiko98/qobuz-dl/blob/bba6f3a71a74ac4d955571de02d8653f19bfa389/qobuz_dl/metadata.py#L41-L42
