### ISSUE TITLE
Suggestion: auto-download all albums by an artist

### ISSUE THREAD

**Issue by PcChip** [vitiko98/qobuz-dl#5]
When I search for an artist, I get at most 10 albums listed (along with 10 tracks below it)  
However there's no way to tell how many albums that artist actually has   
  
Is there a way to enter an artist's name, and have it automatically download all albums by that artist?

**Comment by vitiko98** [comment]
Not yet, but I'll work on it soon.

**Comment by vitiko98** [comment]
Artist support were added for URL input mode.
