### ISSUE TITLE
Invalid Request Signature parameter

### ISSUE THREAD

**Issue by habar0** [vitiko98/qobuz-dl#56]
Just wanted to try this out, but unfortunately it doesnt work.
After entering credentials , its not possible to login.

Error during login: Invalid app secret.
Reset your credentials with 'qobuz-dl -r'.
Resetting doesnt help...

Futher analysis shows it is coming from qoby, there is a http 400 error for each request made.
Invalid Request Signature parameter (signature here)  
Could be related to app_id or secrects I think? 

Anything we can do?

**Comment by Dinosaurier1** [comment]
Unfortunately the same thing here, "Invalid app secret".
Didn´t found the way to update values... Thanks for helping!

**Comment by zozzza** [comment]
After a simply login from the website it works for me again.

**Comment by zozzza** [comment]
@vitiko98 
```
Traceback (most recent call last):
  File "/home/user/.local/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/qobuz_dl/cli.py", line 135, in main
    qobuz.initialize_client(email, password, app_id, secrets)
  File "/home/user/.local/lib/python3.8/site-packages/qobuz_dl/core.py", line 80, in initialize_client
    self.client = qopy.Client(email, pwd, app_id, secrets)
  File "/home/user/.local/lib/python3.8/site-packages/qobuz_dl/qopy.py", line 39, in __init__
    self.cfg_setup()
  File "/home/user/.local/lib/python3.8/site-packages/qobuz_dl/qopy.py", line 203, in cfg_setup
    raise InvalidAppSecretError("Invalid app secret.\n" + RESET)
qobuz_dl.exceptions.InvalidAppSecretError: Invalid app secret.
Reset your credentials with 'qobuz-dl -r'
```
@habar0 @Dinosaurier1 I
t works randomly, try to run `qobuz-dl` several time.

**Comment by Asutaroto** [comment]
I confirm the problem with the download

**Comment by Dinosaurier1** [comment]
@zozzza 
O.k., thank you! I tried it several times now, and - it works!

**Comment by zozzza** [comment]
> @zozzza
> O.k., thank you! I tried it several times now, and - it works!

I hope he can fix this quickly (@vitiko98)!

**Comment by zozzza** [comment]
@habar0 @Dinosaurier1 @Asutaroto 
No issue today!

**Comment by zozzza** [comment]
@vitiko98 
Please check your inbox!
