### ISSUE TITLE
downloaded files not 100% "bitperfect" 

### ISSUE THREAD

**Issue by Ghoost666** [vitiko98/qobuz-dl#59]
Hello, first thanks for the awesome programm, working flawlessly.
i was flashed when i found it, since it worked right away and it sounds hearable better than CD Rips
now i thought as a "final test" to compare a qobuz-dl downloaded file to a file which is actually downloaded from qobuz (bought) and i really hoped to get same sizes, so it would be the exact same file, but it isnt, the qobuz-dl downloaded file is a little smaller.
best case would be if somehow some microseconds are cut on either end but i dont think so.
atleast i cant make out a hearable difference...
I just wanted to report this in case it wasnt observed yet since it isnt true 100% "bitperfect"

**Comment by vitiko98** [comment]
Thanks for the report. That may be releated to FLAC compression level, but I'm not sure. Spectral comparisons will clear your doubts.

In any case, there's nothing we can do about it, since we specifically fetch data from Qobuz API.
