### ISSUE TITLE
This release is not streamable

### ISSUE THREAD

**Issue by zozzza** [vitiko98/qobuz-dl#62]
```
Error getting release: This release is not streamable
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/qobuz_dl/core.py", line 113, in download_from_id
    downloader.download_id_by_type(
  File "/home/user/.local/lib/python3.8/site-packages/qobuz_dl/downloader.py", line 205, in download_id_by_type
    raise NonStreamable("This release is not streamable")
qobuz_dl.exceptions.NonStreamable: This release is not streamable
```
The release I tried to download is not yet available, it will be released on February 26th so #54 is broken?

**Comment by vitiko98** [comment]
Did the program stop after that? Please confirm, the exception output is part of the logger.

**Comment by zozzza** [comment]
@vitiko98 Yes of course!

**Comment by vitiko98** [comment]
Upgrade ant try again.

**Comment by zozzza** [comment]
@vitiko98 OK, now it works, no traceback! Thank you so much.
Is it possible to get the skipped ID of releases at the end of the downloads? Do I have to open a new "issue '?

**Comment by zozzza** [comment]
@vitiko98 OK, now it works, no traceback! Thank you so much.
Please check ~> #63
