### ISSUE TITLE
Where can i find config.ini?

### ISSUE THREAD

**Issue by Leigo6677** [vitiko98/qobuz-dl#66]
I'm using Google Colaboratory
I tried to look for the said file location but I can't find it

**Creating config file: /root/.config/qobuz-dl/config.ini**

**Config file updated. Edit more options in /root/.config/qobuz-dl/config.ini**

Do you know where to find this? So I don't have to repeat login process everytime.

**Comment by vitiko98** [comment]
Not sure how Google Colaboratory works, but I suppose you can cat the created file to watch its content: 

`cat /root/.config/qobuz-dl/config.ini`
