### ISSUE TITLE
Multiple Genre tags

### ISSUE THREAD

**Issue by Vinnyl-mugs** [vitiko98/qobuz-dl#68]
Genre like this makes your library hard to organize

![image](https://user-images.githubusercontent.com/78894539/107607666-d033e480-6c74-11eb-9ff2-29bb8fae089d.png)

One genre is good enough. Thanks!

**Comment by vitiko98** [comment]
This is the data returned from Qobuz API. `qobuz-dl` can't listen to the music and say "this is Hip Hop and nothing else". Not only that, but I bet a lot of users don't want a single genre tag.

I recommend you to use an external tool like `beets` to get better genre tags and don't rely on Qobuz API.
