### ISSUE TITLE
Windows - program crashes when file exists

### ISSUE THREAD

**Issue by PcChip** [vitiko98/Qobuz-DL#7]
instead of overwriting (or not) , the program crashes if a file already exists (thus losing all of your search results that were queued for downloading)

**Comment by vitiko98** [comment]
Can you attach an screenshot or paste the output?

Thanks

**Comment by PcChip** [comment]
metadata.py, line 41 (os.rename)  
  
FileExistsError: [WinError 183] Cannot create a file when that file already exists  
  
https://i.imgur.com/sOVJTQM.png

**Comment by vitiko98** [comment]
It should be fixed now. Thanks for reporting it!
