### ISSUE TITLE
Long playlists?

### ISSUE THREAD

**Issue by davidaamesjr** [vitiko98/qobuz-dl#72]
I have a playlist that's around 950 songs, yeah I know it's stupid, but anyways 500 get Queued then the download "completes" with around only 300 finished and when I try again it just skips all and says the releases have been already downloaded... any ideas? Thanks

**Comment by davidaamesjr** [comment]
sdfsdf

**Comment by vitiko98** [comment]
This was discussed before and it looks like a limitation from Qobuz API. 

In any case, such download amounts might be perceived as abuse from Qobuz. I recommend you to split your playlists and reduce the amount of downloads in short periods. This is for the greater good!

**Comment by davidaamesjr** [comment]
I figured as much, I was a little brazen in my quest haha.  Thanks.

**Comment by davidaamesjr** [comment]
Any tips on how to split a qobuz playlist in to separate parts or edit it?
