### ISSUE TITLE
Label (fun/interactive mode)

### ISSUE THREAD

**Issue by zozzza** [vitiko98/qobuz-dl#75]
Search in interactive mode is limited to: 
```
Albums
Tracks
Artists
Playlists
```
Why not add `Labels` too? Can it work? 
Thank you so much once again.

**Comment by vitiko98** [comment]
Hey, join to discuss it: https://discord.gg/GVBwyY9u4N

**Comment by zozzza** [comment]
> Hey, join to discuss it: https://discord.gg/GVBwyY9u4N

Expired! Email me the link.

**Comment by awsms** [comment]
why was it closed?

**Comment by xeruf** [comment]
also wondering
