### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by kingdariud01** [vitiko98/qobuz-dl#9]
I cannot get qo-dl yo run on windows 10. I followed the steps from the how to but no luck. Can some post some easy steps to get the tool to run on windows 10? Thanks

**Comment by vitiko98** [comment]
Can you paste the output or post screenshots?

**Comment by kingdariud01** [comment]
Good morning, i tried to follow the steps for windows 10. Everything went
well untill I got to run qobuz-dl then I got the message that such file
does not exist. I have phyton 3.9 installed and pip3 enabled. I run the
command lines from powershell. Maybe I am doing something wrong? I will
screen shots later today for I don't have access to my computer as we
speak. Thanks for your help.

F. Dariós
