### ISSUE TITLE
Problem with creating config file

### ISSUE THREAD

**Issue by georgetan1107** [vitiko98/qobuz-dl#97]
I could not create my config file successfully. It always told me there was a value error, but I don't know where the error occurs. I've linked a screenshot of it. Could someone please help me fix this issue?
![image](https://user-images.githubusercontent.com/80540577/114379452-b102e780-9b3d-11eb-8a9d-006e5d384a24.png)

**Comment by vitiko98** [comment]
@georgetan1107 I suggest you to check the Python environment in your machine. This issue is not related to `qobuz-dl`.
